// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChNonsZBfWb4B_7v-7_3-TdAfkcX8Ovxc',
    appId: '1:760311148250:web:c3d3af30f76c5d9e583fe3',
    messagingSenderId: '760311148250',
    projectId: 'reis-imovel',
    authDomain: 'reis-imovel.firebaseapp.com',
    storageBucket: 'reis-imovel.appspot.com',
    measurementId: 'G-T076PP00X8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH6JChQoS3UahNQjjyEOVc-2ahArOEWp0',
    appId: '1:760311148250:android:7ac58efbfabb8434583fe3',
    messagingSenderId: '760311148250',
    projectId: 'reis-imovel',
    storageBucket: 'reis-imovel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz7d12x0sSzFVjKnEaXI1F4ZT-QgB4AzA',
    appId: '1:760311148250:ios:558a69f21ef99864583fe3',
    messagingSenderId: '760311148250',
    projectId: 'reis-imovel',
    storageBucket: 'reis-imovel.appspot.com',
    iosBundleId: 'com.example.reisImovelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz7d12x0sSzFVjKnEaXI1F4ZT-QgB4AzA',
    appId: '1:760311148250:ios:825bd33da39c7474583fe3',
    messagingSenderId: '760311148250',
    projectId: 'reis-imovel',
    storageBucket: 'reis-imovel.appspot.com',
    iosBundleId: 'com.example.reisImovelApp.RunnerTests',
  );
}
